### PR TITLE
Refactor HAND improvements

### PR DESCRIPTION
**Pull request by jhkennedy**

### CODE REVIEW

**Comment by cirrusasf** [comment]
by comparing our code with the HydroSAR code, I found these are three major differences which impact the HAND result. One, Hydrosar doe snot apply flat pixels fill, before HAND is fill nan, it is also mask by dem_nodata_mask, and the dem_nodata_mask=dem == 0, HydroSAR uses its gdal_write to output the HAND file. If we use write_cog to output the HAND file, the data range are differecent. For example, for test dem file Copernicus_DSM_COG_10_N23_00_E090_00_DEM.tif, data range 0 to 19 by gdal_write, 0-39 by write_cog.

**Comment by cirrusasf** [comment]
In the hydrosar, if verbose=True, it apply flat pixles fill, normaly, it sets the verbose=False, so it does not apply flat pixles fill. Batu suggested to use the flat pixel fill to overcome the negative pixels along the banks of the rivers. 

When hydorsar canclaute the hand, the pgrid initializes with pgrid.nodata=None, after it get the hand of each basin and combines the to HAND, it apply dem_nodata_mask which is dem == 0 the mask the HAND, then fo fill_NAN process. The idea is they think the dem==0 means the ocean or big river connected to the ocean. They does not fill nan for these pixels.

I will check the data range by write_cog and gdal_write.

**Comment by jhkennedy** [comment]
> In the hydrosar, if verbose=True, it apply flat pixles fill, normaly, it sets the verbose=False, so it does not apply flat pixles fill. Batu suggested to use the flat pixel fill to overcome the negative pixels along the banks of the rivers.

So I read that as we should apply it and there's no action necessary, correct?

> When hydorsar canclaute the hand, the pgrid initializes with pgrid.nodata=None, after it get the hand of each basin and combines the to HAND, it apply dem_nodata_mask which is dem == 0 the mask the HAND, then fo fill_NAN process. The idea is they think the dem==0 means the ocean or big river connected to the ocean. They does not fill nan for these pixels.

This is *probably* a bad choice for global HAND -- DEM == 0 is also a vaild value. We'll go back and mask the Ocean pixels in post processing so I'm not sure there's any value to masking zeros. Is this just a performance optimization to prevent filling in the ocean, or do you think there's some other valid reason to do it? We can look at a tile with a lot of ocean and decide if it's necessary to do or not

> I will check the data range by write_cog and gdal_write.

You can use `gdalcompare.py` to compare the output tiffs as well.

**Comment by cirrusasf** [comment]
I suggest: I would like to check if flat fill is necessary, because we use sgrid. 2. I think we may not apply hand[dem_nodata_mask]=nodata_fill_value before we do fill_nan process. 3. I will compare the geotiff by write_cog and gdal_write.

**Comment by cirrusasf** [comment]
I need point out the hydrosar uses acc_thresh=acc.mean, we use acc=100.

**Review by cirrusasf — APPROVED** [review]

**Pull request merged**
